query GetPoolsPancakeLive(
  $first: Int = 100
  $skip: Int = 0
  $totalLocked: BigDecimal = 100
) @live {
  pancake_bsc_3_pools(
    first: $first
    skip: $skip
    orderBy: volumeUSD
    orderDirection: desc
    where: { totalValueLockedUSD_gt: $totalLocked }
  ) {
    id
    token0 {
      id
      symbol
      name
    }
    token1 {
      id
      symbol
      name
    }
    poolDayData(first: 1, orderBy: date, orderDirection: desc) {
      id
      volumeUSD
      date
    }
    token0Price
    token1Price
    volumeUSD
    feeTier
  }

  pancake_eth_3_pools(
    first: $first
    skip: $skip
    orderBy: volumeUSD
    orderDirection: desc
    where: { totalValueLockedUSD_gt: $totalLocked }
  ) {
    id
    token0 {
      id
      symbol
      name
    }
    token1 {
      id
      symbol
      name
    }
    poolDayData(first: 1, orderBy: date, orderDirection: desc) {
      id
      volumeUSD
      date
    }
    token0Price
    token1Price
    volumeUSD
    feeTier
  }
}
