sources:
  - name: uniswap_matic_3
    handler:
      graphql:
        endpoint: https://api.thegraph.com/subgraphs/name/ianlapham/uniswap-v3-polygon
        retry: 3
    transforms:
      - prefix:
          value: uniswap_matic_3_
          includeRootOperations: true
          includeTypes: false
      - autoPagination:
          validateSchema: true
          limitOfRecords: 1000
plugins:
  - pollingLive:
      defaultInterval: 1000
documents:
  - ./graphql/*.gql
serve:
  browser: false
