apiVersion: apps/v1
kind: Deployment
metadata:
  name: miner
spec:
  replicas: 2
  selector:
    matchLabels:
      app: miner
  template:
    metadata:
      labels:
        app: miner
    spec:
      containers:
        - name: miner
          image: 559073480624.dkr.ecr.eu-west-2.amazonaws.com/miner:latest
          ports:
            - containerPort: 3000
          envFrom:
            - configMapRef:
                name: config-map
