sources:
  - name: pancake_bsc_3
    handler:
      graphql:
        endpoint: https://api.thegraph.com/subgraphs/name/pancakeswap/exchange-v3-bsc
        retry: 3
    transforms:
      - prefix:
          value: pancake_bsc_3_
          includeRootOperations: true
          includeTypes: false
      - autoPagination:
        validateSchema: true
        limitOfRecords: 1000

  - name: pancake_eth_3
    handler:
      graphql:
        endpoint: https://api.thegraph.com/subgraphs/name/pancakeswap/exchange-v3-eth
        retry: 3
    transforms:
      - prefix:
          value: pancake_eth_3_
          includeRootOperations: true
          includeTypes: false
      - autoPagination:
        validateSchema: true
        limitOfRecords: 1000

plugins:
  - pollingLive:
      defaultInterval: 1000
documents:
  - ./graphql/*.gql
serve:
  browser: false
