import React, { useState } from "react";
import WebSocketComponent from "./WebSocketComponent";
import Head from "next/head";
import { Inter } from "next/font/google";
import path from "path";
import fsPromises from "fs/promises";
import styles from "@/styles/Home.module.css";
const inter = Inter({ subsets: ["latin"] });

export const getStaticProps = async (context) => {
  const filePath = path.join(
    path.join(process.cwd(), "public", "static", "api-url")
  );
  const buffer = await fsPromises.readFile(filePath);
  const url = Buffer.from(buffer).toString();
  return { props: { url: url } };
};

export default function Home({ url }) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={`${styles.main} ${inter.className}`}>
        <div className={styles.description}>
          <p>HELLO</p>
          <p>{process.env.NEXT_PUBLIC_ENVIROMENT_VAR}</p>
          <p>{process.argv[2]}</p>
          <p>{process.argv[1]}</p>
          <p>{process.argv[0]}</p>
          {url}
          <input
            name="url"
            type="text"
            placeholder="url"
            onChange={(e) => {
              console.log(e);
              setUrl(e.target.value);
            }}
            value={url}
            required
          />
          <WebSocketComponent wsUrl={url}></WebSocketComponent>
        </div>
      </main>
    </>
  );
}
