apiVersion: v1
kind: ServiceAccount
metadata:
  name: sa-default
  namespace: front
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: role-full-access-to-secrets
  namespace: front
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    resourceNames: ["aws-secret"]
    verbs: ["delete"]
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["create"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: default-role-binding
  namespace: front
subjects:
  - kind: ServiceAccount
    name: sa-default
    namespace: front
    apiGroup: ""
roleRef:
  kind: Role
  name: role-full-access-to-secrets
  apiGroup: ""
