apiVersion: v1
kind: Service
metadata:
  name: simple-web-service
  namespace: front
spec:
  selector:
    app: front
  ports:
    - protocol: TCP
      port: 8080
      targetPort: front-port
  type: LoadBalancer
