sources:
  - name: uniswap_eth_3
    handler:
      graphql:
        endpoint: https://api.thegraph.com/subgraphs/name/uniswap/uniswap-v3
        # strategy: race
        retry: 3
    transforms:
      - addSourceName: true
      - prefix:
          value: uniswap_eth_3_
          includeRootOperations: true
          includeTypes: false
      - autoPagination:
        validateSchema: true
        limitOfRecords: 1000
  - name: uniswap2_eth
    handler:
      graphql:
        endpoint: https://api.thegraph.com/subgraphs/name/uniswap/uniswap-v2
        retry: 3
    transforms:
      - addSourceName: true
      - prefix:
          value: uniswap_eth_2_
          includeRootOperations: true
          includeTypes: false
      - autoPagination:
        validateSchema: true
        limitOfRecords: 1000
  - name: uniswap_matic_3
    handler:
      graphql:
        endpoint: https://api.thegraph.com/subgraphs/name/ianlapham/uniswap-v3-polygon
        # strategy: race
        retry: 3
    transforms:
      - addSourceName: true
      - prefix:
          value: uniswap_matic_3_
          includeRootOperations: true
          includeTypes: false
      - autoPagination:
        validateSchema: true
        limitOfRecords: 1000
  - name: uniswap_bsc_3
    handler:
      graphql:
        endpoint: https://api.thegraph.com/subgraphs/name/ianlapham/uniswap-v3-bsc
        # strategy: race
        retry: 3
    transforms:
      - addSourceName: true
      - prefix:
          value: uniswap_bsc_3_
          includeRootOperations: true
          includeTypes: false
      - autoPagination:
        validateSchema: true
        limitOfRecords: 1000

plugins:
  - pollingLive:
      defaultInterval: 1000
documents:
  - ./graphql/GetPoolsUniswap.gql
  - ./graphql/GetPoolsUniswapLive.gql
serve:
  browser: false
