sources:
  - name: uniswap_bsc_3
    handler:
      graphql:
        endpoint: https://api.thegraph.com/subgraphs/name/ianlapham/uniswap-v3-bsc
        # strategy: race
        retry: 3
    transforms:
      - addSourceName: true
      - prefix:
          value: uniswap_bsc_3_
          includeRootOperations: true
          includeTypes: false
      - autoPagination:
          validateSchema: true
          limitOfRecords: 1000
  - name: pancake_bsc_3
    handler:
      graphql:
        endpoint: https://api.thegraph.com/subgraphs/name/pancakeswap/exchange-v3-bsc
        retry: 3
    transforms:
      - prefix:
          value: pancake_bsc_3_
          includeRootOperations: true
          includeTypes: false
      - autoPagination:
          validateSchema: true
          limitOfRecords: 1000
  - name: sushi2_bsc
    handler:
      graphql:
        endpoint: https://api.thegraph.com/subgraphs/name/unchase/sushiswap-bsc
        retry: 5
    transforms:
      - addSourceName: true
      - prefix:
          value: sushi_bsc_2_
          includeRootOperations: true
          includeTypes: false
      - autoPagination:
          validateSchema: true
          limitOfRecords: 1000
plugins:
  - pollingLive:
      defaultInterval: 1000
documents:
  - ./graphql/*.gql
serve:
  browser: false
